import { corsHeader } from "../_shared/cors.ts";

interface SummarizeRequest {
  content: string;
}

interface SummarizeResponse {
  content: string;
  tag: string[];
}

const GEMINI_API_URL =
  "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent";

Deno.serve(async (req: Request) => {
  // Handle CORS preflight request
  if (req.method === "OPTIONS") {
    return new Response("ok", {
      headers: corsHeader,
    });
  }

  try {
    // Get note content from request body
    const { content }: SummarizeRequest = await req.json();

    if (!content?.trim()) {
      return new Response(
        JSON.stringify({
          error: "Content is required",
        }),
        {
          status: 400,
          headers: {
            ...corsHeader,
            "Content-Type": "application/json",
          },
        },
      );
    }

    // Get Gemini API key from Supabase secret
    const apiKey = Deno.env.get("GEMINI_API_KEY");

    if (!apiKey) {
      throw new Error("GEMINI_API_KEY is not configured");
    }

    // Call Gemini
    const geminiResponse = await fetch(GEMINI_API_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-goog-api-key": apiKey,
      },
      body: JSON.stringify({
        contents: [
          {
            role:'user',
            parts: [
              {
                text: `
                Summarize the following note in one or two sentences, and suggest 2-4 short topical tags . Note content:\n\n${content}`
              },
            ],
          },
        ],
        generationConfig: {
          responseMimeType: "application/json",
          responseSchema:{
            type:'OBJECT',
            properties:
          }
        },
      }),
    });

    if (!geminiResponse.ok) {
      const errorText = await geminiResponse.text();

      console.error("Gemini API error:", errorText);

      return new Response(
        JSON.stringify({
          error: "Failed to generate summary",
        }),
        {
          status: 500,
          headers: {
            ...corsHeader,
            "Content-Type": "application/json",
          },
        },
      );
    }

    const geminiData = await geminiResponse.json();

    // Get Gemini generated text
    const generatedText =
      geminiData.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!generatedText) {
      throw new Error("No response generated by Gemini");
    }

    // Convert Gemini JSON string into JavaScript object
    const result: SummarizeResponse = JSON.parse(generatedText);

    return new Response(JSON.stringify(result), {
      status: 200,
      headers: {
        ...corsHeader,
        "Content-Type": "application/json",
      },
    });
  } catch (error) {
    console.error("Function error:", error);

    return new Response(
      JSON.stringify({
        error: error instanceof Error
          ? error.message
          : "Something went wrong",
      }),
      {
        status: 500,
        headers: {
          ...corsHeader,
          "Content-Type": "application/json",
        },
      },
    );
  }
});